### ISSUE TITLE
R studio failed to install the latest development version of hdf5r from Github (win10)

### ISSUE THREAD

**Issue by Sophia409** [hhoeflin/hdf5r#116]
**I install hdf5r following https://github.com/hhoeflin/hdf5r，it shows two methods:**
![image](https://user-images.githubusercontent.com/30619010/52907396-e8e2ad00-329b-11e9-998b-96431b055ba0.png)
**when I use the second method to install from github,it showed many errors：**
![image](https://user-images.githubusercontent.com/30619010/52907457-e0d73d00-329c-11e9-9921-14408bd51967.png)
![image](https://user-images.githubusercontent.com/30619010/52907426-5989c980-329c-11e9-95a6-e122f7196071.png)
The downloaded source packages are in
	‘C:\Users\dell\AppData\Local\Temp\RtmpI7TP9f\downloaded_packages’
√  checking for file 'C:\Users\dell\AppData\Local\Temp\RtmpI7TP9f\remotes8c87faaf3d\hhoeflin-hdf5r-cc278c1/DESCRIPTION'
-  preparing 'hdf5r': (4.9s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (676ms)
-  checking for empty or unneeded directories (1.5s)
-  building 'hdf5r_1.0.1.tar.gz'
   Warning: file 'hdf5r/cleanup' did not have execute permissions: corrected
   Warning: file 'hdf5r/configure' did not have execute permissions: corrected
   
* installing *source* package 'hdf5r' ...
  checking hdf5 headers and libraries
Environment variable LIB_HDF5 is not set. Attempting to download HDF5 files from repository.
试开URL’https://github.com/mannau/h5-libwin/archive/master.zip'
Content type 'application/zip' length unknown
** libs
错误: (由警告转换成)this package has a non-empty 'configure.win' file,
so building only the main architecture
* removing 'D:/soft ware/R-3.5.2/library/hdf5r'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/dell/AppData/Local/Temp/RtmpI7TP9f/file8c863b6795/hdf5r_1.0.1.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
**But when I use the first command:install.packages("hdf5r"), it worked:**
![image](https://user-images.githubusercontent.com/30619010/52907413-23e4e080-329c-11e9-9e32-916eccdb0b2d.png)

Can anyone help me?I search many times ,but I could't find the answer.

**Comment by hhoeflin** [comment]
Could you describe the environment you are on? Under windows - you need a very special set of libraries installed as it needs to compile the c-files against it as well as the compilers used in R. In general, on windows, this is not the recommended way of using it. 

If you are on Win10 and definitely need the development version, I recommend using WSL.

**Comment by Sophia409** [comment]
@hhoeflin hello, thank you for your reply.what said is totally right and I didn't setup the right environment.I have made some attempts,but it was hard and appeared some bugs.You can see it here [mannau/h5-libwin#2](https://github.com/mannau/h5-libwin/issues/2)
My hdf5-1.8.14.zip file obtained from https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.14/src/,then unpack to C:\hdf5, I use the version of cmake-3.13.4-win64-x64 and visual studio 2017 to configure, but it failed! 
And do you mean that I had better change a linux system to do it or use WSL?In fact, I have no experience about this and I don't know how to use WSL.The turorial I follow (https://github.com/mannau/h5-libwin) is so brief that I could't really understand and finish it.Can you give me some advice?

**Comment by Sophia409** [comment]
@hhoeflin  **I downloaded buildhdf5-1.10.4 this time and configure successfully,and according to 3, I have to set these parameters manually. 
But I only find * BUILD_STATIC_EXECS**: check  HDF5_BUILD_CPP_LIB: check * HDF5_BUILD_HL_LIB: check * HDF5_ENABLE_ZLIB_SUPPORT: check **,and I couldn't fould** * CMAKE_BUILD_TYPE: Release *.**
**Also,I don't know how to Set ZLIB, where I need to do**  (ZLIB_INCLUDE_DIR: C:/Rtools/mingw_64/x86_64-w64-mingw32/include
ZLIB_LIBRARY: C:/Rtools/mingw_64/x86_64-w64-mingw32/lib/libz.a).**can you tell me in more detail?**
![image](https://user-images.githubusercontent.com/30619010/52935162-9e445c00-3393-11e9-8fb4-4b24ff945058.png)
![image](https://user-images.githubusercontent.com/30619010/52935447-6689e400-3394-11e9-9d55-fb92d2fd187d.png)

**Comment by hhoeflin** [comment]
My experience with this is also quite limited on windows. @mannau set this up, so maybe he can help you more. In general my recommendation is that
a) Windows is completely fine if you use CRAN packages or simple R packages, even if they need compilation
b) If you use development versions a lot I would definitely recommend linux.

WSL is completely fine for this. In fact, I did a lot of development work for hdf5r in WSL. You can find simple instructions on how to set it up online.
