### ISSUE TITLE
package or namespace load failed for ‘h5’ in dyn.load

### ISSUE THREAD

**Issue by beard1** [hhoeflin/hdf5r#122]
installing to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/h5/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘h5’ in dyn.load(file, DLLpath = DLLpath, ...):
 无法载入共享目标对象‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/h5/libs/h5.so’：:

**Comment by hhoeflin** [comment]
This is the site for the hdf5r package, not h5. Also - with so little information, there is no way to help to debug. Closing this issue for now.
