### ISSUE TITLE
Parallel HDF5

### ISSUE THREAD

**Issue by dipterix** [hhoeflin/hdf5r#125]
Hi, 

How hard it would be to support openMPI version of HDF5 libraries? Or is there any simple installation guide for dummies like me to compile `hdf5r` with parallel version of HDF5 library?

Thanks

**Comment by hhoeflin** [comment]
It would require quite a bit of internal work to enable this. Currently this is not planned as I am not using the package myself anymore. If high speed and parallel IO is very important, I recommend to look into other programming languages than R if possible.
