### ISSUE TITLE
Fix UBSAN complaints

### ISSUE THREAD

**Issue by hhoeflin** [hhoeflin/hdf5r#130]
For the package, there are some complaints from the 
- clang-UBSAN (https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/hdf5r/tests/testthat.Rout)
- gcc-UBSAN (https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/hdf5r/tests/testthat.Rout)

that need to be fixed for re-submission.

**Comment by jeroen** [comment]
The [r-debug](https://github.com/wch/r-debug) docker image is often helpful to reproduce asan/ubsan problems:

```
docker run -it wch1/r-debug
```

It has an `RDsan` and `RDcsan` executable which are builds of r-devel with sanitizers.

**Comment by hhoeflin** [comment]
Thanks - was testing it throught R-hub, but will try this out as well.
