### ISSUE TITLE
Problem trying to install hdf5r

### ISSUE THREAD

**Issue by VicenteFR** [hhoeflin/hdf5r#132]
Hi,

I've tried to install hdf5r having installed hdf5 with Miniconda previously, but I kept getting an error about the usability of a file as reported in [this issue](https://github.com/hhoeflin/hdf5r/issues/113#issue-395971262). Therefore, I've installed the precompiled hdf5 binaries and gave them priority to be called in my environment. With this, I've overcome the issue regarding the file usability, but now I get this errors:

* installing *source* package ‘hdf5r’ ...
** package ‘hdf5r’ successfully unpacked and MD5 sums checked
** using staged installation
checking for a sed that does not truncate output... /bin/sed
checking for gawk... gawk
checking for grep that handles long lines and -e... /usr/bin/grep
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for h5cc... /home/vfajardo/bin/hdf5-1.10.5-linux-centos7-x86_64-shared/bin/h5cc
checking for HDF5 libraries... yes (version 1.10.5)
checking hdf5.h usability... yes
checking hdf5.h presence... yes
checking for hdf5.h... yes
checking for H5Fcreate in -lhdf5... yes
checking for hdf5_hl.h... yes
checking for H5LTpath_valid in -lhdf5_hl... yes
checking for main in -lhdf5_hl... yes
checking for matching HDF5 Fortran wrapper... /home/vfajardo/bin/hdf5-1.10.5-linux-centos7-x86_64-shared/bin/h5fc
Found hdf5 with version: 1.10.5
checking for ggrep... /usr/bin/grep
checking whether /usr/bin/grep accepts -o... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
make: Warning: File `Makevars' has modification time 10 s in the future
cp 1_10_3/*.c 1_10_3/*.h .
gcc -I"/mnt/apps/R/3.6.1/lib64/R/include" -DNDEBUG   -I/usr/local/include -D__USE_MINGW_ANSI_STDIO -fpic  -g -O2  -c const_export.c -o const_export.o
const_export.c: In function ‘show_all_const_data_frame’:
const_export.c:73:73: error: ‘H5F_ACC_SWMR_WRITE’ undeclared (first use in this function)
   ((long long *) REAL(R_const))[CONST_H5F_ACC_SWMR_WRITE] = (long long) H5F_ACC_SWMR_WRITE;
                                                                         ^~~~~~~~~~~~~~~~~~
const_export.c:73:73: note: each undeclared identifier is reported only once for each function it appears in
const_export.c:77:72: error: ‘H5F_ACC_SWMR_READ’ undeclared (first use in this function)
   ((long long *) REAL(R_const))[CONST_H5F_ACC_SWMR_READ] = (long long) H5F_ACC_SWMR_READ;
                                                                        ^~~~~~~~~~~~~~~~~
const_export.c:273:69: error: ‘H5O_INFO_BASIC’ undeclared (first use in this function)
   ((long long *) REAL(R_const))[CONST_H5O_INFO_BASIC] = (long long) H5O_INFO_BASIC;
                                                                     ^~~~~~~~~~~~~~
const_export.c:277:68: error: ‘H5O_INFO_TIME’ undeclared (first use in this function)
   ((long long *) REAL(R_const))[CONST_H5O_INFO_TIME] = (long long) H5O_INFO_TIME;
                                                                    ^~~~~~~~~~~~~
const_export.c:281:73: error: ‘H5O_INFO_NUM_ATTRS’ undeclared (first use in this function)
   ((long long *) REAL(R_const))[CONST_H5O_INFO_NUM_ATTRS] = (long long) H5O_INFO_NUM_ATTRS;
                                                                         ^~~~~~~~~~~~~~~~~~
const_export.c:285:67: error: ‘H5O_INFO_HDR’ undeclared (first use in this function)
   ((long long *) REAL(R_const))[CONST_H5O_INFO_HDR] = (long long) H5O_INFO_HDR;
                                                                   ^~~~~~~~~~~~
const_export.c:289:73: error: ‘H5O_INFO_META_SIZE’ undeclared (first use in this function)
   ((long long *) REAL(R_const))[CONST_H5O_INFO_META_SIZE] = (long long) H5O_INFO_META_SIZE;
                                                                         ^~~~~~~~~~~~~~~~~~
const_export.c:293:67: error: ‘H5O_INFO_ALL’ undeclared (first use in this function)
   ((long long *) REAL(R_const))[CONST_H5O_INFO_ALL] = (long long) H5O_INFO_ALL;
                                                                   ^~~~~~~~~~~~
make: *** [const_export.o] Error 1
ERROR: compilation failed for package ‘hdf5r’

However, I don't really understand how I should declare these variables since, according to the README file from HDF5, I shouldn't change anything. Therefore, I don't really know what to do.

I would appreciate any help. Thanks in advance!

**Comment by levinyi** [comment]
same error

**Comment by mercedes-colomar** [comment]
same error +1

**Comment by rsolano1-uw** [comment]
same error

I am on CentOS 7 with R 4.0.0 and hdf5 1.10.1

**Comment by honghh2018** [comment]
Hi @All
same error happen when install hdf5r
Do kindly man help us to solved this question?
Best wish

**Comment by honghh2018** [comment]
#the hdf5 issue 
@ALL
can anyone could help for this problem?

**Comment by vinettey** [comment]
Same error +1  If anyone know, please kindly help🙏

**Comment by honghh2018** [comment]
@vinettey  I guess it would be the compiler version issue. on my case, the problem once make me crazy for this error that i try the everything i could but it still had no solved. so i totally uninstall R completely and re-install R with same the gcc version. subsequently, i was re-build  the hdf5 library using the same gcc vesion. and the enter R running the install.package('hdf5r',configure.args="--with-hdf5=path/to/your/h5cc"). Finally, it solved my problem.
 I wish it could  help.

**Comment by hhoeflin** [comment]
If you are on CentOS and need to install R and hdf5 etc, I recommend spack.

https://github.com/spack/spack

It offers all versions of R and hdf5 and compiles all of them together from source with the same gcc. Of course other options are possible as well. Tradeoff is that you have to wait a bit until the install is done, but it gives you a lot of control. When compiling hdf5 with spack, request the hdf5 version with 'hl' support, i.e. 

```
spack install hdf5@1.12.0+hl
spack load hdf5@1.12.0+hl
```
In order to avoid compiler difference issues, you can install R with spack as well into the same environment.

**Comment by SiwakornP** [comment]
@SaraMWillis Brilliant. Thank you so much. It's finally solved my case.
