### ISSUE TITLE
Some tests fail with upcoming release of R6

### ISSUE THREAD

**Issue by wch** [hhoeflin/hdf5r#133]
I'm about to submit a new version of R6 to CRAN, but am getting errors with this package when I run checks on reverse dependencies.

Some background: In previous versions of R6, when cloning an object with active bindings, it will extract the function for the active binding at _cloning time_ and put it in the new object. This relied on behavior from `as.list.environment` which apparently was a bug, and will be changed in upcoming versions of R. The bug was that `as.list.environment` would give the function behind an active binding, rather than the value that the function returns when invoked. In upcoming versions of R, it will call the function and return that value.

I have been asked by a Luke Tierney (who is a member of R-Core) to release a new version of R6 which does not rely on the buggy behavior of `as.list.environment`, so that he can fix the bug in R. When the bug is fixed, it will no longer be possible to get the function for an active binding.

In the development version of R6, it separately stores the functions for active bindings when an R6 object is created, and uses those stored functions to create new active bindings when the object is cloned.

Currently, tests for the CRAN version of hd5r fail with the development version of R6.

<details>
  <summary>hd5r check log</summary>

```
Package: hdf5r
Check: tests
New result: ERROR
    Running â€˜testthat.Râ€™ [17s/17s]
  Running the tests in â€˜tests/testthat.Râ€™ failed.
  Complete output:
    > library(testthat)
    > library(hdf5r)
    > 
    > test_check("hdf5r")
    â”€â”€ 1. Error: Subsetting reference vector (@test-reference.R#73)  â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    invalid first argument
    1: ref_obj$clone() at testthat/test-reference.R:73
    2: private$pclone()
    3: copy_slice(old[[i]], new[[i]], old_new_enclosing_pairs[seq.int(i, length(old))], 
           (i == 1))
    4: mget(binding_names, envir = old_slice$binding)
    
    â”€â”€ 2. Error: UI functions for reference vector (@test-reference.R#187)  â”€â”€â”€â”€â”€â”€â”€â”€
    value for 'A' not found
    1: c(r1, r2, r3) at testthat/test-reference.R:187
    2: c.H5R(r1, r2, r3) at testthat/test-reference.R:187
    3: args[[1]]$clone()
    4: private$pclone()
    5: copy_slice(old[[i]], new[[i]], old_new_enclosing_pairs[seq.int(i, length(old))], 
           (i == 1))
    6: mget(binding_names, envir = old_slice$binding)
    7: (function (x) 
       stop(gettextf("value for %s not found", sQuote(x)), call. = FALSE))("A")
    8: stop(gettextf("value for %s not found", sQuote(x)), call. = FALSE)
    
    â•â• testthat results  â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
    [ OK: 956 | SKIPPED: 4 | WARNINGS: 68 | FAILED: 2 ]
    1. Error: Subsetting reference vector (@test-reference.R#73) 
    2. Error: UI functions for reference vector (@test-reference.R#187) 
    
    Error: testthat unit tests failed
    Execution halted
```
</details>

Please install the development version of R6 and release a new version of hd5r which has passing tests.

```R
devtools::install_github('r-lib/R6@rc-v2.4.1')
```

In some cases, errors occur only when the package is loaded the normal way, but not when `load_all()` is used.

Since I have been asked by a member of R-core to submit this fixed version of R6, I want to release it as soon as possible, but this requires that an updated version of hd5r is on CRAN first. Thank you.

**Comment by hhoeflin** [comment]
I will have a look - thanks.

**Comment by wch** [comment]
Update: I just made a fix to the `rc-v2.4.1` branch of R6, and it is possible that it has fixed the issue. If so, apologies for the false alarm!

**Comment by hhoeflin** [comment]
Did you check if it fixed the issue? Thanks

**Comment by wch** [comment]
I think it is working now. When I was working through some of the issues, I found that hdf5r does some unusual things with using `cloneable=FALSE` and copying the default `clone` method as a separate method. Please note that that part of the R6 code shouldn't be considered public, and could change in the future, so it is best to not to do that.

**Comment by hhoeflin** [comment]
yes, I used the "clone" method there as usually my objects need to be non-cloneable, but here I had to do it myself. Is there an "official" way on how I should implement this methodology?

Thanks

**Comment by wch** [comment]
Normally, I would suggest adding a `copy` method that calls `clone`. Are you saying that you don't want `clone` to be public, though?

**Comment by hhoeflin** [comment]
Yeah, in this case I have to ensure that objects can't be cloned (or I have to change the clone method) as I am keeping track of a pointer to HDF5 objects that have to be collected when they are not referenced anymore. 

So in general, all my objects here should be non-cloneable. Just in this one instance, I needed to use it internally in the function myself.
