### ISSUE TITLE
File accessibility error - H5 file not opening from a folder on the server (Z drive)

### ISSUE THREAD

**Issue by ankitaburman** [hhoeflin/hdf5r#146]
Hi,

I am not able to open h5 files from a folder on my server (Z drive). 

The folder containing the h5 file in located on a server (Z drive); I am able to successfully set the working directory to the folder containing the h5 file by using 'Set working directory' in the 'Session' tab and R is able to load other csv files from this folder. However, when I try to load the h5 files, I get the errors listed below:

library(Seurat)
library(tidyverse)
library(dplyr)
library(Matrix)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(hdf5r)
setwd("Z:/Guanling Huang/Projects and Data/AEC2/Single cell/Raw data of 20 samples")
YD141.DATA=Read10X_h5("YD14-1.h5")

Error in H5File.open(filename, mode, file_create_pl, file_access_pl) :

HDF5-API Errors:

error #000: C:\pkg\hdf5-1.8.14\src\H5F.c in H5Fopen(): line 604: unable to open file

class: HDF5

major: File accessibilty

minor: Unable to open file

error #001: C:\pkg\hdf5-1.8.14\src\H5Fint.c in H5F_open(): line 990: unable to open file: time = Fri Mar 27 11:21:12 2020

, name = 'Z:\Guanling Huang\Projects and Data\AEC2\Single cell?\Raw data of 20 samples\YD14-1.h5', tent_flags = 0

class: HDF5

major: File accessibilty

minor: Unable to open file

error #002: C:\pkg\hdf5-1.8.14\src\H5FD.c in H5FD_open(): line 992: open failed

class: HDF5

major: Virtual File Layer

minor: Unable to initialize object

error #003: C:\pkg\hdf5-1.8.14\src\H5FDsec2.c in H5FD_sec2_open(): line 343: unable to open file: name = 'Z:\Guanling Huang\Projects and Data\AEC2\Single cell?\Raw data of 20 samples\YD14-1.h5', errno = 2, error message = 'No such file or directory', class: HDF5

m

Note 1:

However, if I copy paste the folder containing the h5 file onto my desktop, and set the working directory to the folder now on my desktop, R is able to open the h5 file.

setwd("C:/Users/burmana/Desktop/Raw data of 20 samples")
YD141.DATA=Read10X_h5("YD14-1.h5")

Note 2:

If I copy the h5 file and paste it in another folder on the server, R is able to open it. 

Most of my files are on the mentioned folder in the server (Z:\Guanling Huang\Projects and Data\AEC2\Single cell?\Raw data of 20 samples) and I would like to be able to open my h5 files directly from that folder. Since I am able to successfully set the working directory to that folder in the server (Z drive) and open all other files directly from there, I am not sure why I am getting file accessibility/path error while trying to open the h5 files. Do you know of ways that I could try to fix this? Thank you so much for your help.

Best,
Ankita

**Comment by hhoeflin** [comment]
As you can open the files with hdf5r when you copy them local, this is not an issue related to the library. Therefore closing this issue as I won't be able to debug it for you.

In general in my experience drives with spaces in their names are prone to cause errors. But this is just one possible reason and it could be many others. Sorry but I can't help you more.

**Comment by Chestnusaur** [comment]
I had this problem earlier the day as well, and I was downloading the h5 files from our lab's web drive. My supervisor said that it might be also a problem of the h5 files quality, so he directly gave me a copy of the data saved on the hard drive which he is sure that it is good, and everything works out.
