### ISSUE TITLE
`devtools::test` failed

### ISSUE THREAD

**Issue by dipterix** [hhoeflin/hdf5r#178]
I tried `devtools::test()` on github fork. It showed an error:

```
Failure (test-64bit_support.R:88:5): Datatype conversion with 64bit
suppressWarnings(truncateVec(dbl_vec_int64_na, 0, LLONG_MAX)) not equal to res_dbl_uint64_na$output.
'is.NA' value mismatch: 3 in current 2 in target
```

**Comment by hhoeflin** [comment]
Yeah, this has been a bit of a problem lately. the test is supposed to check behaviour with NAs, but there seems to be inconsistencies between platforms. As I don't have an M1 I can't debug this.

**Comment by dipterix** [comment]
Please let me know if I can help. I can fork and test on my machine. 

Also I requested a PR #177 so that you can have github action to check the package for you on osx. A script to install (without brew) is also included in that PR. This might be helpful when brew arch is different from R (for example, ARM brew with x86 R installed, users can compile x86 HDF5 by themselves without having two brews in the same system)

**Comment by hhoeflin** [comment]
Thanks for this - I will merge it. And yes, please debug it, that would be great. Am thankful for help. Personally I have not used this package in years, so am doing this in my spare time as much as I can.

**Comment by dipterix** [comment]
@hhoeflin I don't know how to fix, but I can help you debug, and provide results on M1.

Here's the issue

https://github.com/hhoeflin/hdf5r/blob/5c9074f0d9a19150548a69da01ea342e76db1018/tests/testthat/test-64bit_support.R#L88

![image](https://user-images.githubusercontent.com/8163576/129097003-111a92b9-9456-4485-979f-0e5589bb1203.png)

`2^63+1`, i.e. `LLONG_MAX` is NA in `hdf5r` (I guess this is actually how int64 NA in R is stored?)

All other tests passed.

**Comment by dipterix** [comment]
More information:

Bit information: `9223372036854775807` vs int64 `NA`

```r
> bit64::as.bitstring(dbl_vec_int64_na[18])
[1] "0111111111111111111111111111111111111111111111111111111111111111"

> bit64::as.bitstring(bit64::NA_integer64_)
[1] "1000000000000000000000000000000000000000000000000000000000000000"
```

**Comment by dipterix** [comment]
It seems `2^63` produces different results on M1 vs x86 when converting to `int64_t`. 

* on x86, bit converting `2^63` to `int64_t` is `-9223372036854775808`
* on M1 mac, bit converting `2^63` to `int64_t` is `9223372036854775807`

This little difference cause `bit64` package to interpret `2^63` as `9223372036854775807` instead of `NA` on M1 mac, which I think is their flaw.

I've posted this issue on `bit64` package.

https://github.com/truecluster/bit64/issues/19

Your package seems fine. Small changes on the test might be desired. I'll create a PR soon.

**Comment by dipterix** [comment]
Asked help from `r-devel`, their reply seems confirming my guess: https://stat.ethz.ch/pipermail/r-devel/2021-August/080986.html

`bit64` is handling an undefined conversion, and `hdf5r` is doing right.

**Comment by hhoeflin** [comment]
Great - thanks for following up on this. If this is truly undefined, then
yes I think bit64 needs to handle this as per your pull request. Over the
weekend I have some time and will review and merge all this. Thanks for all
your work!
