### ISSUE TITLE
install hdf5r fail in  centos7.9

### ISSUE THREAD

**Issue by honghh2018** [hhoeflin/hdf5r#210]
Hi developer,

I want to install.package("hdf5r") and the failed 
the install string
install.packages("hdf5r", configure.args = "--with-hdf5=/share/apps/syssoft/library/hdf5-1.12.0/bin/h5cc")
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘hdf5r’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/share/apps/R/R-4.1.2-4/lib64/R/library/00LOCK-hdf5r/00new/hdf5r/libs/hdf5r.so':
  /share/apps/syssoft/library/hdf5-1.12.0/lib/libhdf5_hl.so.200: undefined symbol: HDfprintf
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/share/apps/R/R-4.1.2-4/lib64/R/library/hdf5r’
* restoring previous ‘/share/apps/R/R-4.1.2-4/lib64/R/library/hdf5r’

The downloaded source packages are in
	‘/tmp/RtmpY62GcV/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:

libhdf5_hl.so.200: undefined symbol: HDfprintf

Best,hanhuihong

**Comment by hhoeflin** [comment]
This hdf5 library in /share/apps/syssoft/library seems a non-standard install. Not sure how I can help there.
