### ISSUE TITLE
Check manual and browser based help

### ISSUE THREAD

**Issue by hhoeflin** [hhoeflin/hdf5r#49]
Need to check that the built-in browser based help is working properly

Need to go through the manual and check for any issues.

**Comment by mannau** [comment]
I think we should implement an automated check for R6 methods (+parameters) on the documentation generated like in e.g. `tools::undoc` for S4 classes.

**Comment by hhoeflin** [comment]
This may be a very useful tool. How much work do you think this is?

I think this is a very useful contribution to R overall for R6 classes - but as such it may be coordinated somewhat with the core R team?

On my priority list I would personally rather include some additional functionality in hdf5r than an automatic checking tool.

**Comment by hhoeflin** [comment]
Put intro to package at the beginning

**Comment by mannau** [comment]
- Updated **h5** related doc 87b427d.
- Corrected typos f7318ca
- Removed -class from doc links to improve readability ee6ede3f
