### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by hhoeflin** [hhoeflin/hdf5r#50]
The readme could be more informative

At several places it is out of date or pointing to an incorrect repo

**Comment by hhoeflin** [comment]
Small note: We are supporting only 1.8.13 or above at the moment. Readme still says 1.8.12.

**Comment by mannau** [comment]
Maybe we should add a section Custom INSTALL Parameters and outline an example?
I had a few questions from anaconda users struggling with the hdf5 libraries used.

**Comment by hhoeflin** [comment]
Sounds like a good idea. Do you have some specific examples in mind?

**Comment by mannau** [comment]
I think the most common issue here is for users with anaconda (and hdf5/h5py) installed who want to use a different version of hdf5. We could also create a new issue and leave the current README for 1.0.0 as is.

**Comment by hhoeflin** [comment]
ok agreed.
