### ISSUE TITLE
AdressSanitizer Warning: left shift of negative value

### ISSUE THREAD

**Issue by mannau** [hhoeflin/hdf5r#55]
```
R CMD build .;docker run --cap-add SYS_PTRACE -v "$(pwd):/mnt" f023928cf1d8 /bin/bash -c "cd /mnt; Rdevel CMD check *.tar.gz;cat /mnt/hdf5r.Rcheck/00install.out"
```
```
convert.c:2324:58: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
      if((ll_ptr[i] > MAX_INT_DOUBLE_PREC || ll_ptr[i] < MIN_INT_DOUBLE_PREC) && ll_ptr[i] != NA_INTEGER64 ) {

./convert.h:31:35: note: expanded from macro 'MIN_INT_DOUBLE_PREC'
#define MIN_INT_DOUBLE_PREC (-1LL << 53)
```

**Comment by mannau** [comment]
Hi Holger,
the Sanitizer warning is now fixed now (see https://github.com/hhoeflin/hdf5r/commit/4de064508d3850ac5d3e8e7da214b443855d63bb).
I simply replaced the shifted numbers with constants (for now).
Could you explain why MAX_INT_DOUBLE_PREC and MIN_INT_DOUBLE_PREC are restricted to 53Bit (instead of e.g. LLONG_MAX, LLONG_MIN+1)? 
Cheers,
mario

**Comment by hhoeflin** [comment]
Yes - it is intended to be "MAXimum INTeger that a DOUBLEprecision variable can hold.

Maybe I should have made that clearer in the comment. This variable is used to decide when you would need the bit64 package in order to represent an integer without losing precision.
