### ISSUE TITLE
Review NOTE Non-FOSS package license (file LICENSE)

### ISSUE THREAD

**Issue by mannau** [hhoeflin/hdf5r#64]
We should check the NOTE for  `Non-FOSS package license.`
Is there a reason why the Apache license is used or could be also use BSD_2_clause + file LICENSE?

**Comment by hhoeflin** [comment]
Yes - Novartis requires the Apache license so I can't move away from it.
Sorry

**Comment by mannau** [comment]
no worries- just wanted to make sure.
Apache should be fine...

> Am 21.09.2017 um 07:13 schrieb hhoeflin <notifications@github.com>:
> 
> Yes - Novartis requires the Apache license so I can't move away from it.
> Sorry
>
