### ISSUE TITLE
show method hangs with large datasets/files

### ISSUE THREAD

**Issue by mojaveazure** [hhoeflin/hdf5r#82]
The `show` method hangs when connected to a large HDF5 file. My HDF5 file has three 27,000 x 1,300,000 matrices and is roughly 91 GB on disk.

```R
> library(hdf5r)
> hfile <- h5file('myfile.h5', 'r')
> hfile # hangs
> hfile[['group']] # hangs
> hfile[['group/dataset']] # hangs
> hfile[['group/dataset']]$dims # works
> hfile[['group/dataset']][1:5, 1:5] # works
> names(hfile[['group']]) # works
```

Please note that it only hangs on groups with a matrix in them. When looking at groups without one of these matrices, the `show` method works (I have two other groups that contain arrays of either 27,000 or 1,300,000 in length and `show` is instantaneous).

I've tried this on a variety of computers, running Ubuntu 16.04.3 LTS and macOS 10.11-10.13

The `show` method works, albeit taking ~45 seconds, when viewing an HDF5 file with one 27,000 x 1,300,000 matrix, taking up approximately 37 GB disk space.

I don't know if it's the size of the matrix, size of the file on disk, or some combination of the two that causes `show` to fail.

**Comment by hhoeflin** [comment]
thanks. Can you tell me a little more about the file? Can you share a short script to create it or let me know which chunking it uses etc? Will try to recreate it.

**Comment by mojaveazure** [comment]
Can I get an email to share it with you, or use the email listed in the description? It's a private dataset that isn't ready to be public yet.

**Comment by hhoeflin** [comment]
Sure - please send me an email at my maintainer email address for the package listed on CRAN. Thanks

Also hdf5 version could be helpful, in case it is related to a that.

**Comment by hhoeflin** [comment]
Can you have a look at the branch in pull request #87 and see if this solves the issue? I tried it out on the loom-file, but couldn't do it on the further processed files.

**Comment by mojaveazure** [comment]
It seems to be working and working well. Thank you for your help!

```R
> library(loomR) # Wrapper for working with loom-formatted HDF5 files
Loading required package: R6
Loading required package: hdf5r
Loading required package: iterators
Loading required package: itertools
> h5attributes # Ensure that new function takes place, looking for $num_attrs
function (x) 
{
    if (inherits(x, "H5File")) {
        num_attrs <- x$obj_info()$num_attrs
    }
    else {
        num_attrs <- x$attr_get_number()
    }
    attr_data <- vector("list", length = num_attrs)
    names(attr_data) <- h5attr_names(x)
    for (i in seq_along(attr_data)) {
        attr_obj <- x$attr_open_by_idx(i - 1, ".")
        attr_data[[i]] <- attr_obj$read()
    }
    return(attr_data)
}
<environment: namespace:hdf5r>
> lfile <- loomR::connect(filename = 'loom_1.3M_layers.loom', mode = 'r') # Open the loom file, uses `show` to load H5D objects into lists
> lfile
Class: loom
Filename: /home/hoffmanp/loom_1.3M_layers.loom
Access type: H5F_ACC_RDONLY
Attributes: chunks, version
Listing:
      name    obj_type    dataset.dims dataset.type_class
 col_attrs   H5I_GROUP            <NA>               <NA>
    layers   H5I_GROUP            <NA>               <NA>
    matrix H5I_DATASET 1300774 x 27998          H5T_FLOAT
 row_attrs   H5I_GROUP            <NA>               <NA>
> lfile$layers # The really big datasets are in layers
$norm_data
Class: H5D
Dataset: /layers/norm_data
Filename: /home/hoffmanp/loom_1.3M_layers.loom
Access type: H5F_ACC_RDONLY
Datatype: H5T_IEEE_F64LE
Space: Type=Simple     Dims=1300774 x 27998     Maxdims=Inf x Inf
Chunk: 32 x 32

$scale_data
Class: H5D
Dataset: /layers/scale_data
Filename: /home/hoffmanp/loom_1.3M_layers.loom
Access type: H5F_ACC_RDONLY
Datatype: H5T_IEEE_F64LE
Space: Type=Simple     Dims=1300774 x 27998     Maxdims=Inf x Inf
Chunk: 32 x 32

> lfile$layers$norm_data
Class: H5D
Dataset: /layers/norm_data
Filename: /home/hoffmanp/loom_1.3M_layers.loom
Access type: H5F_ACC_RDONLY
Datatype: H5T_IEEE_F64LE
Space: Type=Simple     Dims=1300774 x 27998     Maxdims=Inf x Inf
Chunk: 32 x 32
```
