### ISSUE TITLE
R error about installing hdf5 uses outdated Homebrew instruction (OS X)

### ISSUE THREAD

**Issue by DMRoberts** [hhoeflin/hdf5r#93]
On OS X, if the user doesn't have the hdf5 library installed, hdf5r prints an error message about how to install it via Homebrew:

        '- OS X using Homebrew: 'brew install homebrew/science/hdf5'

However this Homebrew instruction printed is outdated, as homebrew/science has been deprecated, and hdf5 is now available in Homebrew core.

**Comment by givison** [comment]
Seconding this issue, found this very confusing. I see the updated instructions on your github page, which was how I eventually figured it out. Would be much more helpful if the correct instructions were printed during installation
