### ISSUE TITLE
hdf5r won't install (via CRAN) on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by ecoquant** [hhoeflin/hdf5r#94]
`g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o hdf5r.so const_export.o datatype_export.o Wrapper_auto_H5A.o Wrapper_auto_H5.o Wrapper_auto_H5D.o Wrapper_auto_H5DS.o Wrapper_auto_H5E.o Wrapper_auto_H5F.o Wrapper_auto_H5G.o Wrapper_auto_H5I.o Wrapper_auto_H5IM.o Wrapper_auto_H5L.o Wrapper_auto_H5LT.o Wrapper_auto_H5O.o Wrapper_auto_H5P.o Wrapper_auto_H5R.o Wrapper_auto_H5S.o Wrapper_auto_H5TB.o Wrapper_auto_H5T.o Wrapper_auto_H5Z.o Wrapper_auto_H5FDcore.o Wrapper_auto_H5FDfamily.o Wrapper_auto_H5FDlog.o Wrapper_auto_H5FDsec2.o Wrapper_auto_H5FDstdio.o convert.o hdf5r_init.o H5Error.o H5ls.o Wrapper_manual_H5T.o -L/home/jgalkows/anaconda3/lib -L. -lhdf5_hl -lhdf5 -lz -lm -L/usr/lib/R/lib -lR
installing to /home/site-library/hdf5r/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for 'hdf5r' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/site-library/hdf5r/libs/hdf5r.so':
  libhdf5_hl.so.10: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/home/site-library/hdf5r'

The downloaded source packages are in
        '/tmp/Rtmpqd6kWv/downloaded_packages'
Warning message:
In install.packages(c("hdf5r")) :
  installation of package 'hdf5r' had non-zero exit status
`

**Comment by hhoeflin** [comment]
Could you give more information on how you installed hdf5?

**Comment by ecoquant** [comment]
I did it the same way as on Windows.  Is there another package I need to apt-get or something for HDF5 on Ubuntu? If so, _mea culpa_ on the issue, and can you tell me where to get it?

**Comment by ecoquant** [comment]
That is simply `install.packages(c("hdf5r"))`

**Comment by hhoeflin** [comment]
It assumes that hdf5 is installed included its headers. On Ubuntu 14.04, this requires installing it from source, as far as I know (haven't run this for a while). 

Earlier in the install procedure, it tells you about the HDF5 version - what it is writing?

**Comment by ecoquant** [comment]
Oh, it _does_ have them ... `HDF5 libraries... yes (version 1.8.17)`

**Comment by hhoeflin** [comment]
Usually you so 

sudo apt-get install libhdf5-dev

however on Ubuntu 14.04, the HDF5-version installed is usually too old. The configure script should have complained earlier in the install-process.

From the error, it sounds like your installation has a recent config, but doesn't include the 'high-level' functions that are needed 

libhdf5_hl

**Comment by ecoquant** [comment]
`jgalkows@bos-lpmcy:~$ sudo apt-get install libhdf5-dev
[sudo] password for jgalkows: 
Sorry, try again.
[sudo] password for jgalkows: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libhdf5-dev is already the newest version.
libhdf5-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
jgalkows@bos-lpmcy:~$ 
`

**Comment by ecoquant** [comment]
I think I'm dead ... Just tried to install HDF5 anew from source, and it says my CMake has to be 3.10. The best I can get from my apt-get chain is 2.8.12.2.

**Comment by ecoquant** [comment]
Not _hdf5r_'s problem.

**Comment by arcolombo** [comment]
How did you solve this issue, I am installing hdf5r on Ubuntu 14.04 and am having the same issue with the outdated HDF5 version (1.8.11) error.  did you install 1.8.12 from source using CMAKE?  I could only find the pre-compiled binaries and do not know how to update the hdf5 path (when running sudo, my default path is /usr/bin).

thankyou for any advice

**Comment by smoretti** [comment]
I got the same error on CentOS7 with HDF5 version 1.8.17, gcc 6.1.1 and R 3.4.2

At configure time libhdf5_hl.so and libhdf5.so are found properly.
At compile time everything looks fine, no warning at all.
But during test or package loading I got the same error.

I fixed that by using
```
export LD_PRELOAD=/usr/lib64/libhdf5.so:/usr/lib64/libhdf5_hl.so
```
before starting R (for hdf5r installation or hdf5 loading)


It is strange that running ldd on **hdf5r/libs/hdf5r.so** does not show any calls to libhdf5

**Comment by vondoRishi** [comment]
@arcolombo I have just now installed HDF5 version (1.8.20) in Ubuntu 14 from source [code](https://support.hdfgroup.org/HDF5/release/obtain518.html) . I have used following codes for this , pay attention to **prefix**

`./configure --prefix=/usr --enable-fortran --enable-cxx`   
`make`
`make check`
`sudo make install`

now from R console you can install hdf5r 
`install.packages("hdf5r")`

**Comment by Bio-designer** [comment]
I downloaded an old version of hdf5r from https://cran.r-project.org/src/contrib/Archive/hdf5r/, and solved the problem of outdated HDF5 version.

**Comment by dipterix** [comment]
Check [this link](https://github.com/beauchamplab/rave/blob/master/inst/markdowns/Installation_questions.md#hdf5-requires-at-least-version-xxxxxx) (use LinuxBrew)

Install brew:

```
sudo apt-get install build-essential curl file git
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

To add brew to path in the future

```
test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
test -r ~/.bash_profile && echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.bash_profile
echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.profile
echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.bash_profile
echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.bashrc
brew install hello
```

Install gcc v5 if version is too low

```
brew install gcc@5
```

Install HDF5 library

```
brew install hdf5
```

In R, install hdf5r. Make sure you find h5cc path

```
# One of the following two works
install.packages(
  'hdf5r',
  configure.args = '--with-hdf5 [YOUR h5cc PATH]',
  type = 'source'
)

install.packages(
  'hdf5r',
  configure.args = 'with-hdf5',
  configure.vars = '[YOUR h5cc PATH]'
)
```

**Comment by smoretti** [comment]
I cannot fix it this way

**Comment by dipterix** [comment]
@smoretti have you tried specifying `h5cc` path in `configure.vars`? The problems I met are:

1. `hdf5r` cannot find hdf5 libraries (system missing hdf5 and `brew install hdf5` should solve this problem)
2. `hdf5` library version is too low. This is because the built packages in Ubuntu 14 are too low and you have to manually install hdf5 
3. even if `hdf5` library is installed, `install.packages(hdf5r)` cannot find library path. You have to specify `h5cc` or `h5pcc` path, `which h5cc` should show you the path.
4. Cannot compile or gcc version is not right (use gcc version 5 works for me)

If you cannot resolve the problem in my way. You can have a look at `travis_setup.sh` ([link](https://github.com/hhoeflin/hdf5r/blob/master/travis_setup.sh)) in the github repo. This is what the author uses for compiling hdf5 in a 3rd party build test platform.

```
wget "https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-$HDF5_VERSION/hdf5-$HDF5_VERSION/src/hdf5-$HDF5_VERSION.tar.gz"
  tar -xzf "hdf5-$HDF5_VERSION.tar.gz"
  cd "hdf5-$HDF5_VERSION"
  ./configure --prefix=/usr/local
  sudo make install
  cd ../hdf5r
```

Replace `$HDF5_VERSION` with your desired version. You can find them [here](https://github.com/hhoeflin/hdf5r/blob/master/.travis.yml) (env: matrix:)

**Comment by smoretti** [comment]
I use Fedora with hdf5 version 1.8.17, gcc 6.1.1 and now R 3.5.1 (but in non-regular paths).
hdf5 libraries are found, as well as h5cc.

Everything works fine till
```
building package indices
```
Then R tries to load hdf5r and it fails "testing if installed package can be loaded"

**Comment by hhoeflin** [comment]
I use WSL as a testing environment as well. Here is a repo where I download and install hdf5 from source using environment modules to make various versions available on demand

https://github.com/hhoeflin/wsl-devel-setup

Hope that may help a bit

**Comment by yueqiw** [comment]
Hi,

I encountered the same issue. It turns out the default HDF5 on my machine is linked to the one from anaconda. Although it's version `1.8.17`, installing `hdf5r` this way doesn't work. 
```
......
checking for h5cc... /home/yueqi/anaconda/bin/h5cc
checking for HDF5 libraries... yes (version 1.8.17)
......
```

The solution is to force R to use the HDF5 from `sudo apt-get install libhdf5-dev`. 

1. run `locate h5cc` in the terminal to see a list of h5cc paths. In my case, `libhdf5-dev` correspond to `/usr/bin/h5cc`

2. `install.packages("hdf5r", configure.args="--with-hdf5=/usr/bin/h5cc")`

Now you will see the following
```
checking Using provided HDF5 C wrapper... /usr/bin/h5cc
checking for HDF5 libraries... yes (version 1.10.4)
```

This solved the installation issue. Hope if helps!

**Comment by IamViditAgarwal** [comment]
> 2\. install.packages("hdf5r", configure.args="--with-hdf5=/usr/bin/h5cc")

This solved my issue. Thanks for this suggestion. 
I was figuring out the steps for installing the hdf5r for the past couple of days but couldn't get a reliable solution

**Comment by thinh-tran** [comment]
Have you figured out how to solve this issue? Hdf5r is also failing at the testing step with the same error message for me, not sure how to fix it. Thanks!

> I still have the same issue in my case, compilation is successful but not the testing step
> 
> ```
> checking Using provided HDF5 C wrapper... /software/bin/h5cc
> checking for HDF5 libraries... yes (version 1.8.17)
> checking hdf5.h usability... yes
> checking hdf5.h presence... yes
> checking for hdf5.h... yes
> checking for H5Fcreate in -lhdf5... yes
> checking for hdf5_hl.h... yes
> checking for H5LTpath_valid in -lhdf5_hl... yes
> checking for main in -lhdf5_hl... yes
> checking for matching HDF5 Fortran wrapper... /software/bin/h5fc
> Found hdf5 with version: 1.8.17
> ```
> 
> ```
> ** testing if installed package can be loaded
> Error: package or namespace load failed for 'hdf5r' in dyn.load(file, DLLpath = DLLpath, ...):
>  unable to load shared object '/builddir/build/BUILDROOT/R351-hdf5r-1.0.1-1.el7.x86_64/software/R/3.5.1/lib64/R/library/hdf5r/libs/hdf5r.so':
>   /builddir/build/BUILDROOT/R351-hdf5r-1.0.1-1.el7.x86_64/software/R/3.5.1/lib64/R/library/hdf5r/libs/hdf5r.so: undefined symbol: H5T_STD_U16LE_g
> ```
> 
> I must say I build hdf5r in a mock environment (used to build RPM packages)

**Comment by smoretti** [comment]
I have to use 
`export LD_PRELOAD=/usr/lib64/libhdf5.so:/usr/lib64/libhdf5_hl.so`
as mentioned before to make it works

**Comment by TianTTL** [comment]
I used 
` export LD_PRELOAD=/usr/lib/libhdf5.so:/usr/lib/libhdf5_hl.so`
to solve the problem like 
`unable to load shared object '***/R/library/00LOCK-hdf5r/00new/hdf5r/libs/hdf5r.so': undefined symbol: H5Pget_core_write_tracking`

**Comment by P-G-Park** [comment]
I used
```
sudo R
```
then installed hdf5r

**Comment by breadyangg** [comment]
conda install -c anaconda hdf5
