### ISSUE TITLE
Cannot save h5 attributes as strings

### ISSUE THREAD

**Issue by mase5** [hhoeflin/hdf5r#96]
Hi,
I'm trying to save some strings as main h5 attributes (at root of the hdf5 file) in R with the following code: 
```
file.h5$create_attr(attr_name = "test"
                 , robj = "Hello world!"
                 , dtype = H5T_STRING$new(size = Inf))
```
But then when I read the hdf5 file in python, it tells me that actually this attribute was saved as a byte array i.e.: `[b'Hello world!']`

Anyone an idea how to solve this problem?

**Comment by hhoeflin** [comment]
Please see this. 

https://github.com/h5py/h5py/issues/379

This seems to be a known h5py issue.
