### ISSUE TITLE
Need cat.H5RefClass method to be implemented

### ISSUE THREAD

**Issue by dipterix** [hhoeflin/hdf5r#99]
```
f = hdf5r::H5File$new(file_name, 'r')
id = f$id
hdf5r::H5File$new(id = id)
```

Error:
```
New count is  Error in cat("New count is ", new_count, "\n") : 
  argument 2 (type 'environment') cannot be handled by 'cat'
```

**Comment by hhoeflin** [comment]
Hi, 

creating a new object that has exactly the same id as the old object is really not recommended. The id parameter is for internal use. The reason is that using it this way can easily throw off the object counter.
